runtime: php55
api_version: 1

handlers:
- url: /.*
  script: index.php

- url: /(.*\.css)
  mime_type: text/css
  static_files: /assets/css/
  upload: /assets/css/(.*\.css)



- url: /(.*\.js)
  mime_type: text/javascript
  static_files: /assets/js/
  upload: /assets/js/(.*\.js)


# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: /assets/images/
  upload: /assets/images/(.*\.(bmp|gif|ico|jpeg|jpg|png))
